# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.BooleanField(default=False),
        ),
    ]
